### ISSUE TITLE
no executable permission of Louvain/linux-* files

### ISSUE THREAD

**Issue by LisaSikkema** [dpeerlab/PhenoGraph#11]
Hi there!

Just upgraded my PhenoGraph with pip install -U PhenoGraph, and after that I got an error when running PhenoGraph, stating that permission was denied to my [path_to_env]lib/python3.7/site-packages/phenograph/louvain/linux-convert file. Same for the other two linux- files in that folder.
After changing permissions to those three files with chmod +x, the error was solved. 
Not sure if it was a glitch in my system or a problem with the PhenoGraph package, but maybe you guys could check :)

**Comment by levrex** [comment]
I had the exact same issue. You can indeed fix the error easily with chmod +x.

**Comment by hisplan** [comment]
Hi,

Sorry for the late reply. We're not sure if this is related to PhenoGraph or Louvain. We're going to close this for now, but please reopen if you encounter this issue again.
