### ISSUE TITLE
Latest version PG 1.5.7 does not work with latest requirement Leiden 0.8.2

### ISSUE THREAD

**Issue by YubinXie** [dpeerlab/PhenoGraph#12]
I updated my Phenograph to 1.5.7 in order to work with latest scipy version which is required by latest scanpy. A Leiden >=0.8.2 was installed as part of PhenoGraph requirement. However, after testing, I believe there is some change in the latest Leiden that leads to Phenograph failure. 

Downgrading leiden to 0.8.1 works.

**Comment by hisplan** [comment]
@YubinXie I tried with `pip install leidenalg==0.8.7` (which appears to be the latest version), and it worked fine.

Would you please try again with the latest version?

**Comment by YubinXie** [comment]
I have a working version now and would try to not mess it up... will report again if it happens again.
