### ISSUE TITLE
Incompatibility scipy > 1.4.2

### ISSUE THREAD

**Issue by prubbens** [dpeerlab/PhenoGraph#14]
PhenoGraph seems to break down with the newest versions of scipy (1.5 and 1.6). When running the algorithm, the following error occurs: 

`TypeError: Expected list, got numpy.ndarray`

Full error code can be found here: https://github.com/theislab/scanpy/issues/1407

Any ideas or updates on how to resolve this?

**Comment by hisplan** [comment]
Which version of PhenoGraph are you using? Did you try with PhenoGraph v1.5.7?

**Comment by JulienVerdier** [comment]
@hisplan For me it didn't work with v1.5.2 but it does work indeed with v1.5.7 (I also mentioned it in [theislab/scanpy#1407](https://github.com/theislab/scanpy/issues/1407))

**Comment by hisplan** [comment]
Thanks. Closing this.
