### ISSUE TITLE
Issue with multiprocessing

### ISSUE THREAD

**Issue by giacomos97** [dpeerlab/PhenoGraph#15]
Hello,
I have installed PhenoGraph 1.5.7 together with the required libraries.
PhenoGraph breaks when trying to run the [example notebook](https://github.com/dpeerlab/PhenoGraph/blob/master/examples/example-using-random-data-points.ipynb) not "line by line" but in full (have a try with this: [PhenoGraph_demo_random.zip](https://github.com/dpeerlab/PhenoGraph/files/6213474/PhenoGraph_demo_random.zip)). 
Indeed, PhenoGraph crashes during internal execution of _sort_by_size_ function, starting an infinite loop in which 4 identical plots are created.

When I set _n_jobs = 4_ or I omit that parameter, the execution crashes during Neighbors computation:
![1](https://user-images.githubusercontent.com/28544922/112673565-29428b00-8e65-11eb-92da-0dc590675b5a.png)

Instead, if I set _n_jobs = 1_, the execution stops at _sort_by_size_ function:
![2](https://user-images.githubusercontent.com/28544922/113557385-38140500-95fe-11eb-89b3-8d6d13ccd719.png)
 
In both cases the error, related to multiprocessing, is the following:

![3](https://user-images.githubusercontent.com/28544922/112673888-8f2f1280-8e65-11eb-9994-421c8f8141c3.png)

How could we solve that?

**Comment by pedrofale** [comment]
I have the same issue. Would be great to know what's going on!

**Comment by giacomos97** [comment]
Hi! 
In some cases I avoided this issue by executing PhenoGraph in the _main_  function like this
    
    if __name__ == '__main__':
       communities, graph, Q = phenograph.cluster(X, k = 30, n_jobs = 4)

instead of just

    communities, graph, Q = phenograph.cluster(X, k = 30, n_jobs = 4)

Nevertheless it seems more like a partial workaround than a real solution. Any idea on that?

**Comment by hisplan** [comment]
Were you running this in Jupyter Notebook? If so, you might want to take a look at this ticket:
https://github.com/dpeerlab/PhenoGraph/issues/1

Please let us know if this helps.

**Comment by giacomos97** [comment]
Had this issue while running either inside Spyder, Jupyter Lab or via console (python and ipython commands).
I only managed to run PhenoGraph thanks to its Scanpy implementation.

**Comment by hisplan** [comment]
Closing this.
