### ISSUE TITLE
Best k value to use 

### ISSUE THREAD

**Issue by dalide** [dpeerlab/PhenoGraph#18]
Hi, I have a question about the parameter k, the number of nearest neighbors to use, is there a way to choose the best k value? like comparing the modularity for each k and choose based on some criteria. Thanks.

**Comment by quantumkisa** [comment]
i saw some guides concerning dat problem. https://github.com/dpeerlab/PhenoGraph/blob/master/examples/tutorial_pbmc3k.ipynb

**Comment by dalide** [comment]
> i saw some guides concerning dat problem. https://github.com/dpeerlab/PhenoGraph/blob/master/examples/tutorial_pbmc3k.ipynb

Thanks a lot, this is very helpful.
