### ISSUE TITLE
Error when using sparse matrix as input to cluster

### ISSUE THREAD

**Issue by ManuSetty** [dpeerlab/PhenoGraph#2]
I tried using a precomputed sparse kernel as input to `phenograph.cluster` and it failed with the attached error 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/2151404/82397376-52f97d00-9a1e-11ea-91b9-e4ea6ad022da.png">

**Comment by hisplan** [comment]
It says the shapes are different: 314 vs. 341. Do you still have this issue?
