### ISSUE TITLE
Sample notebook/code

### ISSUE THREAD

**Issue by rgranit** [dpeerlab/PhenoGraph#3]
Hi, Is there some place where once can find some sample code or jupyter notebook example including some test dataset to analyze?

Thanks!

**Comment by hisplan** [comment]
Hi,

Sorry for the late response. Here's one example using random data points:
https://github.com/dpeerlab/PhenoGraph/blob/dev/examples/example-01-using-random-data-points.ipynb

You can certainly try with something like 10x PBMC dataset which is publicly available.

Thanks!

**Comment by hisplan** [comment]
Here's another example using the 10x PBMC 3k dataset: https://github.com/dpeerlab/PhenoGraph/blob/master/examples/tutorial_pbmc3k.ipynb
